# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://alias/api/customers
Content-Type: application/json

{
  "name": "Иванов Иван Иванович",
  "customer_id": "1",
  "phone": "1234567890",
  "gender": "M",
  "birthDay": "20",
  "birthMonth": "3",
  "birthYear": "1986"
}

###

POST http://alias/api/customers
Content-Type: application/json

{
  "name": "Анна",
  "customer_id": "2",
  "phone": "0987654321",
  "gender": "F",
  "birthDay": "20",
  "birthMonth": "3"
}

###

POST http://alias/api/customers
Content-Type: application/json

{
  "name": "Мария Соколова",
  "customer_id": "789654321",
  "phone": "789654321",
  "gender": "F",
  "birthDay": "31",
  "birthMonth": "1"
}

###
